spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:~/test3
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    locations: classpath:/db/migration

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

jwt:
  secret_key: t33Th0FsH4rK4R3Sh4Rp4sFck
  issuer: org.itrex.java.lab
  expiration_millis: 86400000